name: Scrape latest data

# ✅ Allow GitHub Actions to push code changes
permissions:
  contents: write

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repo
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: Fetch latest data
    - name: Fetch latest data
      run: curl "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv" -o usgs_current.csv

    # Step 3: Install pandas
    - name: Install requirements
      run: python -m pip install pandas

    # Step 4: Run your Python script
    - name: Run script to create main csv
      run: python get_all_data.py

    # Step 5: Debug - show file diff (optional)
    - name: Show diff
      run: git diff --stat

    # Step 6: Commit and push if there are changes
    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
